# Generated by Django 5.0.3 on 2024-03-20 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0004_delete_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('description', models.TextField()),
                ('cost', models.TextField()),
                ('duration', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('category', models.TextField()),
                ('photo', models.ImageField(upload_to='media/events')),
                ('website', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_from_events_app', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_from_events_app', to='venues.venue')),
            ],
        ),
    ]
