# Generated by Django 5.0.3 on 2024-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
